### ISSUE TITLE
Specify a system time search

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#10]
Dependency: #9 

A system time search will be specified using either one or two vertical bars, plus a drop-down to select an [Allen](http://docs.marklogic.com/guide/temporal/searching#id_98704) or [ISO](http://docs.marklogic.com/guide/temporal/searching#id_92200) operator. 
- Display all operators plus "None" in a drop-down
- If the currently selected operator requires a date/time range, show two vertical bars
- If the currently selected operator requires a single date/time, show one vertical bar
- If the currently selected operator is "None", show no vertical bars
- The user must be able to slide the bar(s) left and right
- Based on the location of the bars and the currently selected operator, display the corresponding cts query. 
- On clicking the Search button (#8), include a valid time query if the operator is something other than "None"

**Comment by dmcassel** [comment]
@hils124, @ashleydattalo please modify so that the cts query gets updated when the bars are moved or a new operator gets selected.

**Comment by ghost** [comment]
Finished this
