### ISSUE TITLE
Specify a valid time search

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#11]
Dependency: #9 

A valid time search will be specified using either one or two horizontal bars, plus a drop-down to select an Allen or ISO operator.
- Display all operators plus "None" in a drop-down
- If the currently selected operator requires a date/time range, show two vertical bars
- If the currently selected operator requires a single date/time, show one vertical bar
- If the currently selected operator is "None", show no vertical bars
- The user must be able to slide the bar(s) left and right
- Based on the location of the bars and the currently selected operator, display the corresponding cts query.
- On clicking the Search button (#8), include a valid time query if the operator is something other than "None"

**Comment by dmcassel** [comment]
@hils124, @ashleydattalo please modify so that the cts query gets updated when the bars are moved or a new operator gets selected.

**Comment by ghost** [comment]
Finished this
