### ISSUE TITLE
Specify the data to display

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#13]
On the logical document visualization, each box has a label based on the value of the physical document's JSON property "data". Allow the user to specify what single JSON property or XML element of the physical documents will be displayed in the boxes. 
- Add a text input, label ("Document Property"), and "Display" button
- On button click, update the display to show the values of the specified document property. 
- If the property/element is not found, show a "No such property/element" message.

**Comment by dmcassel** [comment]
Look in bitemp_graph.js for "d.content.data" -- that's the hard-coded reference to the data JSON property.

**Comment by jmakeig** [comment]
Next step would be to allow a user to look at the document and select a property, rather than having to type it in.

**Comment by dmcassel** [comment]
Yes. Future ticket.

**Comment by dmcassel** [comment]
Please verify that after selecting a new property for the display, the color functionality remains the same. That means that physical documents with different display values will have different colors.

**Comment by dmcassel** [comment]
Colors are not working. @lrhruska, please revisit this one.

**Comment by lrhruska** [comment]
@dmcassel I'll get on this one first

**Comment by lrhruska** [comment]
@dmcassel I think this ticket is closed, I'll start the newly created ticket #40 with the drop down menu

**Comment by dmcassel** [comment]
This ticket isn't closed yet, because after selecting a property, the new display does not provide different colors for different values.

**Comment by kmcostel** [comment]
I think this ticket is complete, return color(d.content[displayProperty]), is choosing the displayProperty and redrawing correctly when different properties are selected.
