### ISSUE TITLE
Editing a document works on Mac, but not Linux or Windows

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#23]
#7 is complete for the user interface and works correctly on the Mac. However, the Node.js middle tier is not passing along the body of the PUT request when running on Windows or Linux. This results in a MarkLogic-level error:

> Status 500: XDMP-NOMATCH: No matches for cts:element-reference(fn:QName("","sysStart"),("type=dateTime")) in document{}

**Comment by dmcassel** [comment]
@kmcostel this should work now; could you please test?

**Comment by hils124** [comment]
I tested it on Windows and it works, so the ticket should be finished
