### ISSUE TITLE
Have index.html display based on a URL parameter

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#24]
By default, index.html shows addr.json. Based on #5, the user can type a URL and see that logical document displayed. Add code to drive that functionality from a URL parameter, as "/?collection=foo.json". This will allow the search page (#8) to set up links to logical documents.

**Comment by ghost** [comment]
Dave, Hilary and I just finished this. We're working on getting the graph on the search page now.

**Comment by dmcassel** [comment]
I need a pull request from you -- the previous one was accepted, so it closed.

**Comment by ghost** [comment]
Okay. We sent a new pull request
