### ISSUE TITLE
Create a document

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#36]
Provide the ability for the user to create a new temporal document (ie, a document with a new URI, not just editing an existing document). This functionality will be on index.html. 
- present the list of available temporal collections to the user
- user selects a temporal collection
- identify the axes required for documents in that collection
- provide an input box for the document URI
- provide a textarea for document content
- pre-populate the text area with the appropriate axis JSON properties or XML elements (sysStart, sysEnd, valStart, valEnd)
- provide Save and Cancel buttons
- after successful Save, update the display to show this new logical document
- after a failed Save, display an error message to the user

Before beginning work, present your ideas for the UI to Dave.

**Comment by kmcostel** [comment]
@dmcassel Please check if this works
