### ISSUE TITLE
Visually indicate the result of clicking on a physical document

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#38]
In the graph on index.html, provide a visual indication after selecting a physical document. Display the URI of the document above the Edit/View/Delete buttons, with a label that says, "Selected URI:". 

Clicking a document should also cause the outline of that document to have thicker lines. (I haven't checked whether d3 allows that, but it probably does.)

**Comment by kmcostel** [comment]
This is working for the most part. There's a visual issue for some/most documents with shared borders.

**Comment by kmcostel** [comment]
Lukas' pull request also adds onto this
