### ISSUE TITLE
Add drop down list with possible properties to change the text in the graph

### ISSUE THREAD

**Issue by lrhruska** [marklogic/bitemp-explorer#40]
Rather than having a textbox, create a drop down menu, so that the user only has to choose and click a property rather than think and type and click.

**Comment by dmcassel** [comment]
Will this just be for JSON documents, or will it work for XML as well? Either is fine, but if you plan to focus on JSON documents, please add an issue for XML documents that can be worked on later. 

Remember that documents can be complex, having more than just the dateTimes and a single data property. For you test data, [please generate some more complex data](http://www.json-generator.com/) and select properties from those.

**Comment by lrhruska** [comment]
Right now I have it working for just JSON so I will add an issue. 

I may also add an issue for the complex data depending on how my testing goes.
