### ISSUE TITLE
Axes set up for start + 5 or 10 years

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#46]
setupXAxis() in bitemp_graph.js specifies a range of sysStart through sysStart + 10 years. setupYAxis() specifies valStart through valStart + 5 years. Most likely this is because some of the End years are infinity (year 9999). Fix this so that the range is sysStart through sysEnd, excluding any infinity dates. Fall back on sysStart + 10 years if all sysEnd dates are infinity. Apply the fix to the X and Y axes.

**Comment by kmcostel** [comment]
Dibs
