### ISSUE TITLE
Modify code to work for different strings representing the timestamps (index page)

### ISSUE THREAD

**Issue by lrhruska** [marklogic/bitemp-explorer#56]
Currently, our project is hard-coded to take the specific JSON properties "sysEnd", "valStart" etc.

Modify our code to work (in both XML and JSON) with timestamp property/element names such as "mySystemStart", "startValTime", "myTemporalValidEndTime" etc. 

We can do this by making requests to the Management API (ask for the the axes on the current collection; ask for the properties of each axis) or by making an extension to get these in a single request.

**Comment by lrhruska** [comment]
Blocked here since query console won't accept xQuery XML docs that don't contain the tags "valStart", "sysEnd" etc. QC needs those specific strings for temporal docs or else it won't accept them.

Also, JSON temporal inserts don't work for anything other than 'sysStart' 'valStart' etc.

**Comment by dmcassel** [comment]
@lrhruska, I think it's not accepting anything else because that's how the axes were configured. See buffers 1 and 2 in Fei's MLW1 workspace. For a given temporal collection, the element or property names are fixed by the configuration.

**Comment by lrhruska** [comment]
Ah okay, that explains it. I'll poke around after I finish working with H+A. @dmcassel

**Comment by dmcassel** [comment]
Currently works for index.html, but not yet search.html

**Comment by lrhruska** [comment]
index page works perfectly
