### ISSUE TITLE
Reduce page load time

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#79]
- use .min versions for jQuery, jQuery UI, d3, moment
- currently loading both jquery.min.js and jquery-1.10.2.js. Eliminate one of these and retest. (jquery.min.js is version 2.1.1, so we should probably keep that one)
- move CSS links from body to head

**Comment by kmcostel** [comment]
We're a little unsure about the first bullet point, how do you mean? We can't only load d3.min.js because we use other d3 things in our code?

**Comment by kmcostel** [comment]
Never mind
