### ISSUE TITLE
Create a deploy command

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#83]
Right now, someone using the bitemp explorer has to use curl to deploy the extensions. Replace this with a node command. 
- create a deploy.js (will be run with "node deploy.js")
- have deploy.js properly deploy the extensions in the ext directory
- update the README's instructions
- remove curl.exe (should not be in the repository)

To read a file: 
- use [Node's fs module](https://nodejs.org/api/fs.html); [readFileSync](https://nodejs.org/api/fs.html#fs_fs_readfilesync_filename_options) would be appropriate here
- use [Node's request module](https://github.com/request/request) to send the extension to MarkLogic. This should be equivalent to the curl command in the README

**Comment by ghost** [comment]
Lukas and I finished this

**Comment by dmcassel** [comment]
Let's leave it open until I've had a chance to review and accept the PR.

**Comment by ghost** [comment]
Okay, sounds good. Lukas just submitted a pull request for it
