### ISSUE TITLE
Display system time and valid times

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#9]
Dependency: #8 

On the Search page, display an area that shows the system time range on the horizontal axis and the valid time range on the vertical axis. 
- the range of system and valid times must be based on the range of date/times in the currently specified temporal collection (see #8)
  - this will likely require a [REST API extension](http://docs.marklogic.com/guide/rest-dev/extensions)

**Comment by dmcassel** [comment]
To get the system and valid dateTime ranges, it would be possible to set up a [/v1/values configuration](http://docs.marklogic.com/REST/GET/v1/values/[name]), but that would require asking for the min and max for the system and range indexes. That would be four http calls, assuming you knew which indexes to ask for. Better to use a REST extension. The one parameter would be the temporal collection to be used. The extension can then look up the axes and their corresponding indexes, then use [cts.values()](http://docs.marklogic.com/cts.values) to find the min and max (use "limit=1" and ascending/descending options).

**Comment by dmcassel** [comment]
![image](https://cloud.githubusercontent.com/assets/701394/8782694/27975a28-2ee5-11e5-987f-9dacb7e8667f.png)

This wireframe shows what I have in mind. Let me know if you have different ideas. Some notes:
- for #9, just need to show the blank chart, the dateTime ranges for valid and system time, and the "Valid Time" and "System Time" labels to the left of and below the chart
- #10 will handle adding the vertical bars, the system time operator selection, and generating the equivalent system time cts query
- #11 will do the same as #10, but for valid time
- for #9, note that you might want to just show dates, or you might want to show dates and times. I suggest that if the time range is less than 48 hours, show the full date and time
- note that the angle at which the system times are shown is what's available through the wireframing tool

**Comment by ghost** [comment]
Okay looks good. Which ALN and ISO operators would we place in the drop down lists?

**Comment by dmcassel** [comment]
Those will be part of #10 and #11, but the answer is [all the ones listed in the Temporal Guide](http://docs.marklogic.com/guide/temporal/searching#id_78584).

**Comment by ghost** [comment]
Okay, sounds good.
