### ISSUE TITLE
Editing a document requires its temporal collection to have use LSQT set

### ISSUE THREAD

**Issue by kmcostel** [marklogic/bitemp-explorer#90]

**Comment by dmcassel** [comment]
If it's not set, doesn't that just mean that you can't set the system time? If that's correct, it's something you could check for and disable/hide the system time editing in the UI.

**Comment by dmcassel** [comment]
You can determine whether LSQT is enabled through http://localhost:8002/manage/v2/databases/Documents/temporal/collections/lsqt/properties?collection=myTemporal&format=json.
