### ISSUE TITLE
Display whether LSQT is enabled

### ISSUE THREAD

**Issue by dmcassel** [marklogic/bitemp-explorer#91]
In the UI, indicate whether LSQT is enabled. (Use http://localhost:8002/manage/v2/databases/Documents/temporal/collections/lsqt/properties?collection=myTemporal&format=json.) 

Provide a hover-over explanation of what LSQT is.

**Comment by dmcassel** [comment]
@lrhruska still need a hover-over definition for LSQT

**Comment by lrhruska** [comment]
Hil's got it
